@startuml AutoScaleBoardSequence

title Flujo de Auto-Escalado del Tablero (Toggle Button)

actor "Usuario" as User
participant "DOM" as DOM
participant "ToggleButtonView" as View
participant "ToggleButton" as Model
participant "ControllerGame" as Game
participant "ControllerToggleButton" as Controller

== 0. Inicialización ==
Controller -> Controller : initialize()
Controller -> View : new ToggleButtonView()
activate Controller
activate View
View -> View : getElement()
note right: Crea el HTML y añade el listener de\n'click' al checkbox UNA SOLA VEZ
deactivate View
Controller -> DOM : addenventlistener( 'juego-comenzo')
Controller -> DOM : addenventlistener( 'resolvemode')
Controller -> DOM : addEventListener('board-autoscale')
Controller -> DOM : addEventListener('board-reset-default')
deactivate Controller

== 1. Ciclo de vida del boton en la vista ==

Game -> DOM : dispatchEvent('juego-comenzo')
activate DOM
DOM -> Controller : Captura evento 'juego-comenzo'
deactivate DOM
activate Controller
Controller -> View : enableAutoScaleToggle() (Activa el botón)
note right: Solo cambia checkbox.disabled = false
deactivate Controller
Game -> DOM : dispatchEvent('resolvemode')
activate DOM
DOM -> Controller : Captura evento 'resolvemode'
deactivate DOM
activate Controller
Controller -> View : disableAutoScaleToggle() (Desactiva el botón)
note right: Solo cambia checkbox.disabled = true
deactivate Controller

== 2. alternar el estado del botón ==
User -> Controller : Click en el botón "board-autoscale-toggle" handlerAutoEscala()
activate Controller
Controller -> View : toggleVisualState()
deactivate Controller
activate View

alt  el botón pasa a estado ON (Prendido)
    View -> Model : updateButtonState(on)
    View -> Model : getBoardDimensions()
    activate Model
    Model --> View : rows, cols
    deactivate Model
    View -> DOM : dispatchEvent('board-autoscale', {e.detail. rows, cols })
else el botón pasa a estado OFF (Apagado)
    View -> Model : updateButtonState(off)
    View -> DOM : dispatchEvent('board-reset-default')
end
deactivate View

== 3. Comunicación y Actualización ==
DOM -> Controller : handlerEvent('board-autoscale' o 'board-reset-default')
activate Controller

alt Evento: 'board-autoscale'

    Controller -> API : POST /api/ToggleButton/column
    activate API
    Controller -> API : POST /api/ToggleButton/row
    note right: Spring crea un nuevo tablero\ncon las dimensiones solicitadas
    API --> Controller : 200 OK
    deactivate API
else Evento: 'board-reset-default'
    Controller -> API : POST /api/ToggleButton/reset
    activate API
    note right: Spring restaura el tablero\na 6 filas y 7 columnas
    API --> Controller : 200 OK
    deactivate API
end


@enduml
