@startuml conecta4rest

component cliente_web {

  package resources {
    class index <DOM> {}
    class Controller  {}
    class View  {}
    class models {}
    class Mensssages {}
  }


}

component servidor_spring {

  class RestController <@RestController> {}
  class Servis {}
  class model {}
  class Settings <Singleton> {}
  class Game {}
  class Players {}
  class HumanPlayer {}
  class ComputerPlayer {}
  class Board {}
}



Controller *--> View
Controller *--> models 
View *--> models
View ..> Mensssages
View ..> index : ACTUALIZA 
index --> Controller : EVENTOS
Controller --> RestController :GET, POST, PUT, DELETE
RestController ..> Servis
Servis ..> model

Game *--> Players
Game *--> Board
HumanPlayer ..> Board
ComputerPlayer ..> Board
Players *--> HumanPlayer
Players *--> ComputerPlayer



@enduml