@startuml res_ejem10

component cliente_web {
  class ClienteWeb {

  }
  package resources {
    class index {

    }

    class script {

    }
  }
}

component servidor_spring {

  class Application {

  }
  class JpaRepository<< T Item>> {
    save()
    findOne()
    findAll()

  }

  interface ItemRepository {

  }

  class ItemRestController <@RestController> {

    @Autowired
    ItemRepository itemRepository;
  }


  component bbdd {

    class Item <@Entity>{
        id
        nombre
        asunto
        comentario
    }

  }

}

Application *-- ItemRestController

JpaRepository ..> Item :<<bind>> 

JpaRepository <|-- ItemRepository

ItemRestController *-- ItemRepository :<<2>> CONSULTA, CREA, ACTUALIZA, BORRA

ClienteWeb --> index 

index *-- script

script --> ItemRestController :<<1>> ajax get, post, put, delete


ItemRestController --> script :<<3>> rtn json items o response entity<Item, HttpStatus>

script --> index :<<4>> actualiza el dom 




@enduml