

abstract class Menu #lightred{
}

abstract class QuitMenu #lightred{
}

class QuitOption {
}



abstract class BackMenu #lightred{
}

class BackOption {
}

abstract class NavigatorMenu #lightred{
    
}

class NavigatorOption {
}

class ListMenus  {
    Map<String, Menu> listMenus{}
}
note right
    singleton
end note

class MenusMenu {

}

class GoMenuOption {
}


abstract class Option #lightred{
}

class Console {
}





Menu *-left- Option
NavigatorMenu <|-- QuitMenu
NavigatorMenu <|-- BackMenu
QuitMenu <|-- ServiceMenu
QuitMenu *-- QuitOption
BackMenu *-- BackOption
MessagesOption <|-- QuitOption
Option *-left- Console
MessagesOption <|-- BackOption

MessagesOption <|-- ServiceOption 
Option <|-- MessagesOption
MessagesOption *--Messages
MessagesMenu *--Messages
Menu <|-- MessagesMenu

MessagesMenu <|-- NavigatorMenu
NavigatorMenu *-- NavigatorOption
NavigatorMenu *-- ListMenus
MessagesOption <|-- NavigatorOption
NavigatorOption ..> MenusMenu
MenusMenu *-- GoMenuOption
MessagesOption <|-- GoMenuOption
BackMenu <|-- ListServicesMenu
MessagesMenu <|-- MenusMenu



ServiceOption <|-- AddServiceOption
ServiceOption <|-- QueryServiceOption
ServiceOption <|-- ModifyServiceOption
ServiceOption <|-- CancelDateOption
ServiceOption <|-- DeleteServiceOption

ServiceMenu *-- AddServiceOption
ServiceMenu *-- CancelDateOption
ServiceMenu *-- ModifyServiceOption
ServiceMenu *-- QueryServiceOption
ServiceMenu *-- DeleteServiceOption

AddServiceOption ..> ServiceContract

QueryServiceOption ..> QueryServiceMenu
ModifyServiceOption ..> ModifyServiceMenu
CancelDateOption ..> CancelDateMenu
DeleteServiceOption ..> DeleteServiceMenu

ListServicesMenu <|--- CancelDateMenu
ListServicesMenu <|--- ModifyServiceMenu
ListServicesMenu <|--- QueryServiceMenu
ListServicesMenu <|--- DeleteServiceMenu



QueryServiceMenu *-- QueryOption
ModifyServiceMenu *-- ModifyOption
CancelDateMenu *-- CancelOption
DeleteServiceMenu *-- DeleteOption

ServiceOption <|-- QueryOption
ServiceOption <|-- ModifyOption
ServiceOption <|-- CancelOption
ServiceOption <|-- DeleteOption

ModifyOption ..> ModifyRangeMenu
ModifyRangeMenu *-down- EnlargeOption
ModifyRangeMenu *-down- ShiftOption

BackMenu <|-- ModifyRangeMenu
MessagesOption <|-- EnlargeOption
MessagesOption <|-- ShiftOption







class ServiceMenu {
    listServices[]
}

abstract class MessagesOption {
}
abstract class MessagesMenu {
}


abstract class ServiceOption {
}

class AddServiceOption {
}
class QueryServiceOption {
}
class ModifyServiceOption {
}
class CancelDateOption {
}
class DeleteServiceOption {
}




class QueryServiceMenu {
}
class ModifyServiceMenu {
}
class CancelDateMenu {
}
class DeleteServiceMenu {
}


class QueryOption {
}
class ModifyOption {
}
class CancelOption {
}
class DeleteOption {
}

class ModifyRangeMenu {
}

class EnlargeOption {
}

class ShiftOption {
}


abstract class ListServicesMenu {
}




class Messages #4A90E2{
}

class ServiceContract #lightblue {
}

